PROPOSALS: list[str] = [
    "INITIATE EVA UNIT-01 LAUNCH SEQUENCE",
    "AUTHORIZE THIRD IMPACT PROTOCOL",
    "DEPLOY N2 MINE — SECTOR 7",
    "OVERRIDE DUMMY SYSTEM — UNIT 03",
    "ACTIVATE ABSOLUTE TERROR FIELD",
    "INITIATE SELF-DESTRUCT SEQUENCE — NERV HQ",
    "AUTHORIZE INSTRUMENTALITY PROJECT",
    "ENGAGE ANGEL CONTAINMENT PROTOCOL",
    "REVOKE COMMANDER IKARI CLEARANCE LEVEL 4",
    "RELEASE EVANGELION UNIT-00 FROM LOCKDOWN",
    "INITIATE BAKELITE FLOOD — TERMINAL DOGMA",
    "AUTHORIZE SPEAR OF LONGINUS RETRIEVAL",
    "DECLASSIFY DEAD SEA SCROLLS — SECTION 9",
    "SUSPEND HUMAN INSTRUMENTALITY COMMITTEE ACCESS",
    "INITIATE EMERGENCY EVACUATION — TOKYO-3",
    "GRANT SECTION 2 PURSUIT AUTHORIZATION",
]


class ProposalCycler:
    def __init__(self) -> None:
        self._index = 0

    def next(self) -> str:
        proposal = PROPOSALS[self._index]
        self._index = (self._index + 1) % len(PROPOSALS)
        return proposal
